# server directive resides in the http context, which resides in the main context
server {
	# Sets where the server will accept requests: port 443 and all ssl connections
	listen	443 ssl;

	# Sets the server names accepted by this server
	server_name	julberna.42.fr www.julberna.42.fr;

	# Sets the root directory for requests
	root	/var/www/wordpress;

	# Defines files that will be used as index, meaning, file/directory automatically
	# served when a client requests a URL that doesn't specify a specific file
	index	index.php;

	# Determines the server certificate and private key locations
	# The cert is sent to every client that connects to the server
	# and the private key is read by nginx's master process
	ssl_certificate	/etc/nginx/julberna.42.fr.crt;
	ssl_certificate_key	/etc/nginx/julberna.42.fr.key;

	# Limits connections to include only the specified versions
	ssl_protocols	TLSv1.2 TLSv1.3;

	# Both following configurations aim to reduce the CPU processing in the SSL handshake
	# The reuse of SSL sessions avoid SSL handshakes for parallel and subsequent connections
	# and keepalive connections allow for several requests to be sent via one connection
	ssl_session_timeout	10m;
	keepalive_timeout	70;

	# These configure how nginx handles requests for PHP files
	location ~ \.php$ {
		fastcgi_split_path_info	^(.+\.php)(/.+)$;
		fastcgi_pass	wordpress:9000;
		fastcgi_index	index.php;
		include	fastcgi_params;
		fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param	PATH_INFO $fastcgi_path_info;
	}
}
