# Specifies docker-compose version
version: '3'

# Describes how each service will be handled
services:
        nginx:
                build:
                        context: .
                        dockerfile: requirements/nginx/Dockerfile
                container_name: nginx
                ports:
                        - "443:443"
#                depends_on:
#                        - wordpress
                volumes:
                        - ./requirements/nginx/conf/:/etc/nginx/http.d/
                        - ./requirements/nginx/tools:/etc/nginx/ssl/
                        - /home/${USER}/simple_docker_nginx_html/public/html:/var/www/
                restart: always
